# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parser.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\x05price\"\x1b\n\x0cParseRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1e\n\rParseResponse\x12\r\n\x05price\x18\x01 \x01(\x01\x32\x42\n\x08GetPrice\x12\x36\n\tParserWeb\x12\x13.price.ParseRequest\x1a\x14.price.ParseResponseB\x15Z\x13./gen/parser;parserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023./gen/parser;parser'
  _globals['_PARSEREQUEST']._serialized_start=23
  _globals['_PARSEREQUEST']._serialized_end=50
  _globals['_PARSERESPONSE']._serialized_start=52
  _globals['_PARSERESPONSE']._serialized_end=82
  _globals['_GETPRICE']._serialized_start=84
  _globals['_GETPRICE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
