services:
  parser:
    build:
      context: ./PriceParser
    container_name: grpc_parser
    ports:
      - "50051:50051"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bot:
    build:
      context: ./PriceTrackerBot
    container_name: tg_bot
    environment:
      - PYTHONPATH=/app/app
    env_file:
      - ./PriceTrackerBot/.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: shared-net
    external: true