# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import price_pb2 as price__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in price_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PriceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
                '/price.PriceService/AddUser',
                request_serializer=price__pb2.CreateUser.SerializeToString,
                response_deserializer=price__pb2.NewUser.FromString,
                _registered_method=True)
        self.AddProduct = channel.unary_unary(
                '/price.PriceService/AddProduct',
                request_serializer=price__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=price__pb2.CreateProductResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/price.PriceService/Delete',
                request_serializer=price__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=price__pb2.DeleteProductResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/price.PriceService/Get',
                request_serializer=price__pb2.GetProductRequest.SerializeToString,
                response_deserializer=price__pb2.Product.FromString,
                _registered_method=True)
        self.GetUserProducts = channel.unary_unary(
                '/price.PriceService/GetUserProducts',
                request_serializer=price__pb2.GetUser.SerializeToString,
                response_deserializer=price__pb2.ProductListResponse.FromString,
                _registered_method=True)
        self.UpdateTargetPrice = channel.unary_unary(
                '/price.PriceService/UpdateTargetPrice',
                request_serializer=price__pb2.UpdateRequest.SerializeToString,
                response_deserializer=price__pb2.UpdateResponse.FromString,
                _registered_method=True)


class PriceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTargetPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PriceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=price__pb2.CreateUser.FromString,
                    response_serializer=price__pb2.NewUser.SerializeToString,
            ),
            'AddProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProduct,
                    request_deserializer=price__pb2.CreateProductRequest.FromString,
                    response_serializer=price__pb2.CreateProductResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=price__pb2.DeleteProductRequest.FromString,
                    response_serializer=price__pb2.DeleteProductResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=price__pb2.GetProductRequest.FromString,
                    response_serializer=price__pb2.Product.SerializeToString,
            ),
            'GetUserProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProducts,
                    request_deserializer=price__pb2.GetUser.FromString,
                    response_serializer=price__pb2.ProductListResponse.SerializeToString,
            ),
            'UpdateTargetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTargetPrice,
                    request_deserializer=price__pb2.UpdateRequest.FromString,
                    response_serializer=price__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'price.PriceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('price.PriceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PriceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/price.PriceService/AddUser',
            price__pb2.CreateUser.SerializeToString,
            price__pb2.NewUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/price.PriceService/AddProduct',
            price__pb2.CreateProductRequest.SerializeToString,
            price__pb2.CreateProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/price.PriceService/Delete',
            price__pb2.DeleteProductRequest.SerializeToString,
            price__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/price.PriceService/Get',
            price__pb2.GetProductRequest.SerializeToString,
            price__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/price.PriceService/GetUserProducts',
            price__pb2.GetUser.SerializeToString,
            price__pb2.ProductListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTargetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/price.PriceService/UpdateTargetPrice',
            price__pb2.UpdateRequest.SerializeToString,
            price__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
