# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: price.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'price.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprice.proto\x12\x05price\"0\n\nCreateUser\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\tuser_name\x18\x02 \x01(\t\"-\n\x07NewUser\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\tuser_name\x18\x02 \x01(\t\"X\n\x14\x43reateProductRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x14\n\x0ctarget_price\x18\x04 \x01(\x01\"+\n\x15\x43reateProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\"e\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x14\n\x0ctarget_price\x18\x03 \x01(\x01\x12\x15\n\rcurrent_price\x18\x04 \x01(\x01\x12\x12\n\nproduct_id\x18\x05 \x01(\x03\"8\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\";\n\x14\x44\x65leteProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\"\'\n\x15\x44\x65leteProductResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1a\n\x07GetUser\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"7\n\x13ProductListResponse\x12 \n\x08products\x18\x01 \x03(\x0b\x32\x0e.price.Product\"J\n\rUpdateRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x12\n\nproduct_id\x18\x02 \x01(\x03\x12\x14\n\x0ctarget_price\x18\x03 \x01(\x01\" \n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xfc\x02\n\x0cPriceService\x12,\n\x07\x41\x64\x64User\x12\x11.price.CreateUser\x1a\x0e.price.NewUser\x12G\n\nAddProduct\x12\x1b.price.CreateProductRequest\x1a\x1c.price.CreateProductResponse\x12\x43\n\x06\x44\x65lete\x12\x1b.price.DeleteProductRequest\x1a\x1c.price.DeleteProductResponse\x12/\n\x03Get\x12\x18.price.GetProductRequest\x1a\x0e.price.Product\x12=\n\x0fGetUserProducts\x12\x0e.price.GetUser\x1a\x1a.price.ProductListResponse\x12@\n\x11UpdateTargetPrice\x12\x14.price.UpdateRequest\x1a\x15.price.UpdateResponseB\rZ\x0b./gen;Priceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'price_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./gen;Price'
  _globals['_CREATEUSER']._serialized_start=22
  _globals['_CREATEUSER']._serialized_end=70
  _globals['_NEWUSER']._serialized_start=72
  _globals['_NEWUSER']._serialized_end=117
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=119
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=207
  _globals['_CREATEPRODUCTRESPONSE']._serialized_start=209
  _globals['_CREATEPRODUCTRESPONSE']._serialized_end=252
  _globals['_PRODUCT']._serialized_start=254
  _globals['_PRODUCT']._serialized_end=355
  _globals['_GETPRODUCTREQUEST']._serialized_start=357
  _globals['_GETPRODUCTREQUEST']._serialized_end=413
  _globals['_DELETEPRODUCTREQUEST']._serialized_start=415
  _globals['_DELETEPRODUCTREQUEST']._serialized_end=474
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=476
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=515
  _globals['_GETUSER']._serialized_start=517
  _globals['_GETUSER']._serialized_end=543
  _globals['_PRODUCTLISTRESPONSE']._serialized_start=545
  _globals['_PRODUCTLISTRESPONSE']._serialized_end=600
  _globals['_UPDATEREQUEST']._serialized_start=602
  _globals['_UPDATEREQUEST']._serialized_end=676
  _globals['_UPDATERESPONSE']._serialized_start=678
  _globals['_UPDATERESPONSE']._serialized_end=710
  _globals['_PRICESERVICE']._serialized_start=713
  _globals['_PRICESERVICE']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
